const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const generateGuide = () => {
  const guidesDir = path.join(__dirname, "..", "media", "guides");
  if (!fs.existsSync(guidesDir)) fs.mkdirSync(guidesDir, { recursive: true });

  const filePath = path.join(guidesDir, "student_guide.pdf");
  const doc = new PDFDocument({ margin: 50 });
  const stream = fs.createWriteStream(filePath);

  doc.pipe(stream);

  // Title
  doc.fontSize(24).font("Helvetica-Bold").text("CampusHive: Student Event Guide", { align: "center" });
  doc.moveDown();

  // Intro
  doc.fontSize(12).font("Helvetica").text("Welcome to CampusHive! This guide will help you navigate events and manage your registrations effectively.");
  doc.moveDown();

  // Section 1: Finding Events
  doc.fontSize(16).font("Helvetica-Bold").text("1. Finding and Registering for Events");
  doc.fontSize(12).font("Helvetica").text("- Browse the 'Discover Events' page to see all upcoming activities.");
  doc.text("- Filter by category (Technical, Cultural, Sports, etc.) to find what interests you.");
  doc.text("- Click 'Register' on any event to secure your spot. For paid events, follow the payment instructions.");
  doc.moveDown();

  // Section 2: Your Dashboard
  doc.fontSize(16).font("Helvetica-Bold").text("2. Managing Your Journey");
  doc.fontSize(12).font("Helvetica").text("- View all your registrations in 'My Journeys'.");
  doc.text("- Download your Digital Pass (QR Code) to show at the venue for check-in.");
  doc.text("- Check the status of your registrations (Registered, Attended, etc.).");
  doc.moveDown();

  // Section 3: Attendance and Certificates
  doc.fontSize(16).font("Helvetica-Bold").text("3. Certificates and Feedback");
  doc.fontSize(12).font("Helvetica").text("- Once you attend an event, the organizer will mark you as 'Attended'.");
  doc.text("- You can then 'Claim' your certificate directly from the dashboard.");
  doc.text("- If your certificate isn't available, use the 'Nudge' button to alert the organizer.");
  doc.text("- Don't forget to leave feedback for the events you attend!");
  doc.moveDown();

  // Footer
  doc.fontSize(10).font("Helvetica-Oblique").fillColor("gray")
     .text("Generated by CampusHive System. Have a great event experience!", 0, doc.page.height - 100, { align: "center" });

  doc.end();

  stream.on("finish", () => {
    console.log("Guide generated successfully at:", filePath);
    process.exit(0);
  });
};

generateGuide();
